### ISSUE TITLE
Handle branch names with embedded slash

### ISSUE THREAD

**Issue by marionbarker** [loopandlearn/lnl-scripts#50]
### Problem:

I attempted to build a feature branch, in this case `feat/dana` and the embedded slash messed up the folder name for the local clone.

### Desired solution:

Enable the use of the script with any accepted branch character, e.g., `/` or `+`, etc.

### Example:

```
 /bin/bash -c "$(curl -fsSL \
  https://raw.githubusercontent.com/loopandlearn/lnl-scripts/main/BuildTrio.sh)" - "feat/dana" 
```

This is the error message:
```
mkdir: /Users/marion/Downloads/BuildTrio/Trio_feat: No such file or directory
-: line 635: cd: /Users/marion/Downloads/BuildTrio/Trio_feat/dana-240517-1103: No such file or directory
```

The download succeeded but it was located in the ~/Trio folder so no automatic signing was implemented.

**Comment by ebouchut** [comment]
I recently discovered this builtin _bash_ trick:

```shell
BRANCH=feat/dana
echo "${BRANCH//\//_}"
```

- `//`: Replace every
- `\/`: Slash
- `/`: With
- `_`: a Slash 

Replace the underscore (`_`) with whatever character you want to use as a branch-folder separator.

**Comment by ebouchut** [comment]
@bjorkert You were too quick! :smile:
